[versions]
accompanistWebview = "0.36.0"

appcompat = "1.7.1"
daggerAndroid = "2.57.2"
daggerAndroidProcessor = "2.57.2"
hiltWork = "1.3.0"
mockkVersion = "1.13.10"
namespace = "com.prasadvennam.tmdb"
applicationId = "com.prasadvennam.tmdb"
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
versionCode = "1"
versionName = "1.0"
javaVersion = "11"
testRunner = "androidx.test.runner.AndroidJUnitRunner"

agp = "8.13.1"
coilNetworkOkhttp = "3.3.0"
gson = "2.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
junitJupiterApi = "5.13.3"
junitJupiterEngine = "5.13.3"
junitJupiter = "5.13.3"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
loggingInterceptor = "5.3.2"
firebaseCrashlytics = "20.0.3"
googleGmsGoogleServices = "4.4.4"
googleFirebaseCrashlytics = "3.0.6"
firebaseAnalytics = "23.0.0"
firebasePerf = "22.0.4"
googleFirebaseFirebasePerf = "2.0.2"
googleFirebaseAppdistribution = "5.2.0"
material3 = "1.4.0"
mockk = "1.14.6"
navigationCompose = "2.9.6"
cloudy = "0.2.7"
pagingCompose = "3.4.0-alpha04"
pagingRuntime = "3.3.6"
retrofit = "3.0.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
okhttp = "5.3.2"
tensorflowLite = "2.17.0"
roomRuntime = "2.8.4"
truth = "1.4.5"
ui = "1.9.5"
ksp = "2.2.20-2.0.4"
kotlinxDatetime = "0.7.1"
kover = "0.9.3"
# DI
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.3.0"
# Network
jetbrainsKotlinJvm = "2.2.21"
workRuntimeKtx = "2.11.0"
datastore = "1.2.0"
readMoreVersion = "1.9.0"
coreSplashscreen = "1.2.0"
serializationKotlin = "2.2.21"
uiTooling = "1.9.5"
lifecycleProcess = "2.10.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "daggerAndroidProcessor" }
# web view & interceptor
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#splash screen
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
#core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
#navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
#paggination
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
#room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
#coil
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilNetworkOkhttp" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
#gson
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
#compose
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#firebase
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerf" }
#compose
readmore-material3 = { group = "com.webtoonscorp.android", name = "readmore-material3", version.ref = "readMoreVersion" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
#retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
#tensorflow
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
# Test
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#cloudy
cloudy = { module = "com.github.skydoves:cloudy", version.ref = "cloudy" }

# DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "daggerAndroid" }
dagger-compiler= { module = "com.google.dagger:dagger-compiler", version.ref = "daggerAndroid" }




#kotlin date time
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
#datastore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
# Gradle Plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }
google-firebase-firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "googleFirebaseFirebasePerf" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "googleFirebaseAppdistribution" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
#serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationKotlin" }

# Custom plugins
movieverse-kotlin = { id = "movieverse.kotlin.library" }
movieverse-android-compose = { id = "movieverse.android.library.compose" }
movieverse-android-library = { id = "movieverse.android.library" }
movieverse-android-application = { id = "movieverse.android.application" }

[bundles]



coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx",
]



test = [
    "junit-jupiter",
    "junit-jupiter-api",
    "mockk",
    "kotlinx-coroutines-test",
    "truth",
]

test-runtime = [
    "junit-jupiter-engine"
]
